### ISSUE TITLE
pip package is outdated: 1.3

### ISSUE THREAD

**Issue by f-izzo** [Visgean/exif2pandas#1]
Hi @Visgean, thank you for creating this package.
I'm not able to install the latest 1.4 version through pip as the pip package appears to be stuck on version 1.3.

Can you upload the latest 1.4 version to pip?

Thank you!

**Comment by Visgean** [comment]
hey just released a new version.

**Comment by f-izzo** [comment]
Hi, I can confirm that now the 1.5 package from pip is working!

Thank you for fixing this :+1:
